exp_name: food101
dataset_root: ./../datasets/food-101
weight_root: weight
batch_size: 128
model_name: efficientnet_b0
num_classes: 101
start_epoch: 1
epochs: 2
evaluate: false
restart: false
seed: 1
print_freq: 10
log_freq: 10
apex: true
debug: false

optimizer:
  lr: 0.01
  lr_step_size: 1
  lr_gamma: 0.98
  momentum: 0.9
  weight_decay: 1e-5
